### ISSUE TITLE
Is this bugs?

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/memory-game#4] opened 2016-05-09 13:12 UTC
1. Pick two similar letters and first you will see animation that flip them back, and then they disappear.
2. When you win and reload the page, you still see "You win!" message. Maybe it's correct, or may be not. Maybe for this case `Restart` button should be renamed to `Start new game`
3. On mobile after clicking on `Restart` button, it has focus state and keep borders.

**Comment by ivan-kleshnin** [comment] 2016-05-09 13:20
1. Animation "bug".
2. Bug.
3. Your opinion?

**Comment by ivan-kleshnin** [comment] 2016-05-10 06:13
I've changed my mind: **2** is not a bug and I'm going to keep "Restart" title for simplicity.
We can't assign meaningful and consistent behavior to page reloads. But we can ignore them (or make everything look like that). And this is how current engine behaves.

**Comment by ivan-kleshnin** [comment] 2016-05-10 07:37
**1** fixed in 8505052e8faf653e658f963ec3827c8e935fb70e

**Comment by scabbiaza** [comment] 2016-05-10 11:03
1. will try to fix
2. By direct link page doesn't work: `http://localhost:8080/help`

**Closed as completed** 2016-05-26 13:14 UTC
